version: '3.7'
services:
  service-workshop-postgres:
    container_name: workshop-postgres
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - workshop-pg-vol:/var/lib/postgresql/data/
  
  service-workshop-nestjs:
    container_name: workshop-nestjs
    image: workshop-nestjs:1.0.0
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      - service-workshop-postgres
    volumes:
      - ./app/src:/app/src
      - /app/node_modules/
    ports:
      - 3000:3000
    command: [ "sh", "-c", "while :; do sleep 10; done;" ]

volumes:
  workshop-pg-vol:
